from django.urls import path
from . import views

urlpatterns = [
    path("", views.team_list_create, name="team-list-create"),
    path("my-teams/", views.my_teams, name="my-teams"),
    path("workspace/", views.workspace_switcher, name="workspace-switcher"),
    path("<uuid:team_id>/", views.team_detail, name="team-detail"),
    path("<uuid:team_id>/home/", views.team_home, name="team-home"),
    path("<uuid:team_id>/members/", views.team_members, name="team-members"),
    path("<uuid:team_id>/members/remove/", views.remove_member, name="remove-member"),
    path("<uuid:team_id>/invite/", views.create_invite, name="create-invite"),
    path("<uuid:team_id>/join/", views.join_team, name="join-team"),
    path("<uuid:team_id>/pages/", views.team_pages, name="team-pages"),
    path("<uuid:team_id>/pages/<uuid:page_id>/", views.team_page_detail, name="team-page-detail"),
    path("<uuid:team_id>/pages/<uuid:page_id>/lock/", views.lock_page, name="lock-page"),
    path("<uuid:team_id>/pages/<uuid:page_id>/unlock/", views.unlock_page, name="unlock-page"),
    path("<uuid:team_id>/graph/", views.team_graph, name="team-graph"),
    path("<uuid:team_id>/branches/", views.team_branches, name="team-branches"),
    path("<uuid:team_id>/branches/<uuid:branch_id>/action/", views.branch_action, name="branch-action"),
    path("<uuid:team_id>/chat/", views.team_chat, name="team-chat"),
    path("<uuid:team_id>/chat/ai/", views.team_ai_chat, name="team-ai-chat"),
    path("<uuid:team_id>/activities/", views.team_activities, name="team-activities"),
    path("<uuid:team_id>/notifications/", views.team_notifications, name="team-notifications"),
    path("<uuid:team_id>/conflicts/", views.team_conflicts, name="team-conflicts"),
    path("<uuid:team_id>/conflicts/<uuid:conflict_id>/resolve/", views.resolve_conflict, name="resolve-conflict"),
    path("<uuid:team_id>/audit/", views.team_audit, name="team-audit"),
    path("<uuid:team_id>/share-to-team/", views.share_to_team, name="share-to-team"),
    path("<uuid:team_id>/fork-to-personal/", views.fork_to_personal, name="fork-to-personal"),
    path("<uuid:team_id>/search/", views.search_team, name="search-team"),
    path("<uuid:team_id>/transfer-ownership/", views.transfer_ownership, name="transfer-ownership"),
    path("<uuid:team_id>/memory/", views.team_memory, name="team-memory"),
    path("<uuid:team_id>/memory/add/", views.add_team_memory, name="add-team-memory"),
    path("<uuid:team_id>/upload/", views.upload_to_team, name="upload-to-team"),
    path("notifications/<uuid:notification_id>/read/", views.mark_notification_read, name="mark-notification-read"),
    path("invite/<str:code>/", views.accept_invite, name="accept-invite"),
]